[toolchain]
# Stable
# channel = "1.81.0" # rustc 1.81.0
# Nightly
channel = "nightly-2024-07-19"
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src", "rust-docs"]
profile = "minimal"
targets = ["wasm32-unknown-unknown"]