[settings]
timeout = 1000

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 2000
chain = "{{CHAIN}}"
genesis_wasm_path = "{{PARACHAIN_WASM}}"
cumulus_based = true


[parachains.collator]
name = "mandala-collator-1"
command = "mandala"


