[settings]
timeout = 1000

[relaychain]
default_command = "polkadot"
chain = "rococo-local" 
chain_spec_path = "./plain.json"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 2000
chain = "{{CHAIN}}"
cumulus_based = true
force_decorator = "generic-evm"

# First collator - mimics NISKALA_1 from production
[[parachains.collators]]
name = "niskala-collator-1"
command = "mandala"

# Second collator - mimics NISKALA_2 from production
[[parachains.collators]]
name = "niskala-collator-2"
command = "mandala"